// Public API for the connections feature.
export { ConnectionsProvider, useConnections } from './stores/ConnectionsContext'
export { default as ConnectionForm } from './components/ConnectionForm'
export { default as ConnectionAccessPanel } from './components/ConnectionAccessPanel'
export { default as ConnectionDetail, StatusBadge, connectionUrl } from './components/ConnectionDetail'
export { default as DbTypePickerModal, TYPE_LABEL } from './components/DbTypePickerModal'
export { default as ConnectionSwitcherModal } from './components/ConnectionSwitcherModal'
export { default as EnvBadge, ENV_TONE } from './components/EnvBadge'
export { default as ConnectHandshakeDialog } from './components/ConnectHandshakeDialog'
export { useConnectHandshake } from './hooks/useConnectHandshake'
export type { HandshakeFailure } from './hooks/useConnectHandshake'
export { default as ConnectionExportModal } from './components/ConnectionExportModal'
export { default as ConnectionImportModal } from './components/ConnectionImportModal'
export type { ConnectionAccess, ConnectionExport, ImportResult } from './api'
export { getConnectionAccess, setConnectionAccess } from './api'
export { exportConnection, importConnection, readConnectionExportFile, downloadConnectionExport } from './api'
